#!/usr/bin/env bash
# LaunchAgent entry point. Waits for LM Studio backend to come up after login,
# then runs the auto-generated recommended-load.sh from find_parallel.py.
#
# Why a separate wrapper: recommended-load.sh is regenerated by the probe
# (find_parallel.py) on every hardware change. Keeping the boot-specific
# wait/retry logic here means re-running the probe doesn't clobber it.

set -u
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LMS=~/.lmstudio/bin/lms
LOG=/tmp/lmstudio-server.log

log() { echo "[$(date '+%F %T')] $*" >> "$LOG"; }

log "boot-start.sh fired; repo=$REPO_DIR"

# Wait up to 60s for LM Studio backend to respond. It may be coming up in
# parallel with this LaunchAgent if the user has "Launch at login" set.
for i in $(seq 1 30); do
  if "$LMS" status >/dev/null 2>&1; then
    log "lms backend ready (attempt $i)"
    break
  fi
  if [ "$i" = 30 ]; then
    log "lms backend never came up after 60s — bailing"
    exit 1
  fi
  sleep 2
done

# Run the probe-generated load script. Idempotent: unloads first, then loads.
bash "$REPO_DIR/scripts/recommended-load.sh" >> "$LOG" 2>&1
rc=$?
log "recommended-load.sh exited with rc=$rc"
exit $rc
