#!/usr/bin/env bash
# Auto-generated by find_parallel.py on 2026-04-15 21:44:58
# Optimal empirical config for this 18 GB M3 Pro with Claude+Terminal running.

LMS=~/.lmstudio/bin/lms

"$LMS" server start --bind 0.0.0.0 --port 1234 --cors
"$LMS" unload --all 2>/dev/null
"$LMS" load qwen3-coder-30b-a3b-instruct --context-length 32768 --gpu max --parallel 2 -y
"$LMS" load qwen3-1.7b  --context-length 4096 --gpu max --parallel 2 -y
"$LMS" ps
