#!/usr/bin/env bash
# Auto-generated by find_parallel.py on 2026-04-15 21:44:58
# Edited 2026-04-15: HEAVY-only mode. Running HEAVY+TINY together caused swap
# thrash and tool-call timeouts on 18 GB; dropping TINY gives HEAVY the full
# RAM budget. The bridge routes triage/compress to HEAVY as fallback — slower
# per call but no more timeouts / truncated answers.

LMS=~/.lmstudio/bin/lms

"$LMS" server start --bind 0.0.0.0 --port 1234 --cors
"$LMS" unload --all 2>/dev/null
"$LMS" load qwen3-coder-30b-a3b-instruct --context-length 32768 --gpu max --parallel 2 -y
"$LMS" ps
