#!/usr/bin/env bash
# Auto-generated by find_parallel.py on 2026-04-15 21:44:58
# HEAVY-only. Probed on M3 Pro 18 GB: parallel=2, ctx=32768 is the sweet spot.
# Re-run `python3 scripts/find_parallel.py` on different hardware to regenerate.

LMS=~/.lmstudio/bin/lms

"$LMS" server start --bind 0.0.0.0 --port 1234 --cors
"$LMS" unload --all 2>/dev/null
"$LMS" load qwen3-coder-30b-a3b-instruct --context-length 32768 --gpu max --parallel 2 -y
"$LMS" ps
